const REPO=require('path').resolve(__dirname,'..','..');
const PGHOST=process.env.MS_PGHOST||'/var/tmp/mspg', PGPORT=process.env.MS_PGPORT||'5544';
const {newPage,check,done,psql,asUser}=require('../lib/harness.js');
const URL='http://localhost:8765/';
const T=async(p,ms=450)=>p.waitForTimeout(ms);
const card=(p,d)=>p.locator('#list > .item',{has:p.locator('.desc',{hasText:d})});
const btn=(c,name)=>c.locator('.actions .act',{hasText:new RegExp('^'+name+'$')});
const mk=(desc,cat='Coal Despatch',issue='Weather',loc='Siding 1',pri='High')=>asUser('overman1@example.com',`select create_exception((select shift_clock()->>'shift'),'${loc}','${cat}','${issue}','${desc}',45,'${pri}')`);
const db=(sql)=>psql(sql).out;
const open=async(u,extra)=>{const p=await newPage(u+'@example.com',{width:1280,height:1000}); await p.goto(URL+'dashboard.html'); await T(p,700); return p;};
const toast=p=>p.textContent('#toast');
const row=id=>db(`select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'')||'|'||coalesce(started_by_name,'')||'|'||current_priority||'|'||reported_priority from shift_exceptions where description='${id}'`);
(async()=>{
 console.log('=== 6. lifecycle through the buttons (Start, Request closure, Decline, Resolve, Reopen)');
 mk('WF1 lifecycle');
 let o1=await open('overman1'); let c=card(o1,'WF1 lifecycle');
 check('overman1: new record shows Start (and no Resolve)', (await btn(c,'Start').count())===1&&(await c.locator('.act',{hasText:/Resolve|Reopen|Decline/}).count())===0);
 await btn(c,'Start').click(); await T(o1);
 check('Start -> toast + status In progress in DB', /Started\./.test(await toast(o1))&&row('WF1 lifecycle').startsWith('In progress|||Test Overman One'), row('WF1 lifecycle'));
 c=card(o1,'WF1 lifecycle');
 check('after Start: Request closure offered, Start gone', (await btn(c,'Request closure').count())===1&&(await btn(c,'Start').count())===0);
 await btn(c,'Request closure').click(); await c.locator('.formbox textarea').fill('abc'); await c.locator('.formbox .go').click(); await T(o1,150);
 check('closure note under 5 chars refused with a clear message', /at least 5 characters/.test(await c.locator('.formbox').innerText()));
 check('  ...and nothing was sent', !row('WF1 lifecycle').split('|')[1]);
 await c.locator('.formbox textarea').fill('Work verified in the field'); await c.locator('.formbox .go').click(); await T(o1);
 c=card(o1,'WF1 lifecycle');
 check('closure request saved; pill shows who and when', /Closure requested by Test Overman One ·/.test(await c.innerText()), await c.innerText());
 check('overman cannot request closure twice (button gone)', (await btn(c,'Request closure').count())===0);
 const o2=await open('overman2');
 check('overman2 also sees the pending closure', /Closure requested by Test Overman One/.test(await card(o2,'WF1 lifecycle').innerText()));
 let s1=await open('sic1'); c=card(s1,'WF1 lifecycle');
 check('sic1: pending closure shown, Decline + Confirm Resolved offered', /Closure requested by/.test(await c.innerText())&&(await btn(c,'Decline closure').count())===1&&(await btn(c,'Confirm Resolved').count())===1);
 await btn(c,'Decline closure').click(); await c.locator('.formbox textarea').fill('no'); await c.locator('.formbox .go').click(); await T(s1,150);
 check('decline needs a reason of 5+ characters', /at least 5/.test(await c.locator('.formbox').innerText()));
 await c.locator('.formbox textarea').fill('Still leaking at the joint'); await c.locator('.formbox .go').click(); await T(s1);
 c=card(s1,'WF1 lifecycle');
 check('decline: pill gone, DB closure fields cleared', !/Closure requested/.test(await c.innerText())&&row('WF1 lifecycle').startsWith('In progress||'), row('WF1 lifecycle'));
 await o1.reload(); await T(o1,700); c=card(o1,'WF1 lifecycle');
 await btn(c,'Request closure').click(); await c.locator('.formbox textarea').fill('Joint sealed and checked'); await c.locator('.formbox .go').click(); await T(o1);
 await s1.reload(); await T(s1,700); c=card(s1,'WF1 lifecycle');
 await btn(c,'Confirm Resolved').click(); await T(s1);
 c=card(s1,'WF1 lifecycle');
 const r1=row('WF1 lifecycle');
 check('Confirm Resolved works without a second reason; DB: resolved by sic1, closure fields cleared', r1.startsWith('Resolved||Test Shift In-Charge One|'), r1);
 check('Resolved card: no pending-closure pill, shows Resolved by, Reopen offered', !/Closure requested by/.test(await c.innerText())&&/Resolved by Test Shift In-Charge One/.test(await c.innerText())&&(await btn(c,'Reopen').count())===1);
 check('DB: resolved_at set by the server', db(`select resolved_at is not null and closure_requested_at is null from shift_exceptions where description='WF1 lifecycle'`)==='t');
 // overman My history
 await o1.reload(); await T(o1,700); await o1.click('#tab-history'); await T(o1,200);
 check('overman1 My history shows his resolved WF1', (await card(o1,'WF1 lifecycle').count())===1);
 check('  ...and it has no action buttons / remark button for an Overman', (await card(o1,'WF1 lifecycle').locator('.act').count())===0);
 // history section
 c=card(s1,'WF1 lifecycle'); await c.locator('summary',{hasText:'History'}).click(); await T(s1,500);
 const hist=await c.locator('.hist-row').allInnerTexts();
 const order=['Created','Started','Closure requested','Closure declined','Closure requested','Resolved'];
 const acts=hist.map(h=>h.split('\n')[1]||'');
 check('History (oldest first) lists every step with actor and role', order.every((a,i)=>(acts[i]||'').startsWith(a))&&acts.some(a=>/Test Shift In-Charge One \(Shift In-Charge\)/.test(a)), JSON.stringify(acts));
 check('History shows old -> new and the note', hist.some(h=>/→\s+Resolved/.test(h)&&/closure requested by Test Overman One/.test(h))&&hist.some(h=>/Note: Still leaking at the joint/.test(h)));
 await btn(c,'Reopen').click(); await c.locator('.formbox textarea').fill('Leak came back after closing'); await c.locator('.formbox .go').click(); await T(s1);
 const r2=db(`select status||'|'||coalesce(resolved_at::text,'')||coalesce(resolved_by_name,'')||coalesce(closure_requested_by_name,'')||coalesce(started_by_name,'')||coalesce(started_at::text,'') from shift_exceptions where description='WF1 lifecycle'`);
 check('Reopen: Open again, every cycle field cleared in DB', r2==='Open|', r2);
 c=card(s1,'WF1 lifecycle');
 check('reopened card offers Start again', (await btn(c,'Start').count())===1);
 check('audit history kept after reopen', +db(`select count(*) from exception_audit a join shift_exceptions e on e.id=a.exception_id where e.description='WF1 lifecycle' and a.action in ('started','closure_requested','closure_declined','resolved','reopened')`)>=6);

 console.log('=== 7. Resolve WITHOUT a closure request needs a note');
 mk('WF2 no request');
 s1=await open('sic1'); c=card(s1,'WF2 no request');
 await btn(c,'Start').click(); await T(s1); c=card(s1,'WF2 no request');
 check('sic1 can Start; then sees Resolve (not Confirm Resolved)', (await btn(c,'Resolve').count())===1&&(await btn(c,'Confirm Resolved').count())===0);
 await btn(c,'Resolve').click(); await c.locator('.formbox textarea').fill('ok'); await c.locator('.formbox .go').click(); await T(s1,150);
 check('short resolution note refused', /at least 5/.test(await c.locator('.formbox').innerText())&&row('WF2 no request').startsWith('In progress'));
 await c.locator('.formbox textarea').fill('Cleared by the shift crew'); await c.locator('.formbox .go').click(); await T(s1);
 check('resolved with a note; audit records it', row('WF2 no request').startsWith('Resolved||Test Shift In-Charge One')&&+db(`select count(*) from exception_audit a join shift_exceptions e on e.id=a.exception_id where e.description='WF2 no request' and a.action='resolved' and a.note='Cleared by the shift crew'`)===1);

 console.log('=== 8. manager with can_operate vs without');
 mk('WF7 manager start');
 let m2=await open('manager2'); c=card(m2,'WF7 manager start');
 await btn(c,'Start').click(); await T(m2);
 check('manager2 (can_operate) Started it; DB shows who', row('WF7 manager start').startsWith('In progress|||Test Manager Two (operate)'), row('WF7 manager start'));
 const m1=await open('manager1'); c=card(m1,'WF7 manager start');
 check('manager1 (no can_operate) has NO Start/Resolve/Reopen/Decline on the same card', (await c.locator('.act',{hasText:/^(Start|Resolve|Confirm Resolved|Reopen|Decline closure|Request closure)$/}).count())===0);

 console.log('=== 9. priority change and rank lock');
 mk('WF3 priority');
 s1=await open('sic1'); c=card(s1,'WF3 priority');
 check('card shows reported and current priority and the "originally reported" text', /Reported priority: High/.test(await c.innerText())&&/Current priority: High/.test(await c.innerText())&&/originally reported priority/.test(await c.innerText()));
 await btn(c,'Change priority').click();
 const opts=await c.locator('.formbox select option').allTextContents();
 check('priority form offers only the other two priorities', JSON.stringify(opts)===JSON.stringify(['Low','Medium']), JSON.stringify(opts));
 await c.locator('.formbox select').selectOption('Medium'); await c.locator('.formbox textarea').fill('x'); await c.locator('.formbox .go').click(); await T(s1,150);
 check('priority reason under 5 characters refused', /at least 5/.test(await c.locator('.formbox').innerText())&&row('WF3 priority').endsWith('High|High'));
 await c.locator('.formbox textarea').fill('Field check shows less severe'); await c.locator('.formbox .go').click(); await T(s1);
 c=card(s1,'WF3 priority'); const txt=await c.innerText();
 check('after change: current Medium, reported High kept, Last set by / Changed at / Reason shown', /Reported priority: High/.test(txt)&&/Current priority: Medium/.test(txt)&&/Last set by: Test Shift In-Charge One \(Shift In-Charge\)/.test(txt)&&/Changed at:/.test(txt)&&/Reason: Field check shows less severe/.test(txt), txt);
 check('DB: reported priority untouched', row('WF3 priority').endsWith('Medium|High'), row('WF3 priority'));
 const mgr=await open('manager1'); c=card(mgr,'WF3 priority');
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('Low'); await c.locator('.formbox textarea').fill('Manager review, minor'); await c.locator('.formbox .go').click(); await T(mgr);
 check('manager1 may override a Shift In-Charge', row('WF3 priority').endsWith('Low|High'), row('WF3 priority'));
 await s1.reload(); await T(s1,700); c=card(s1,'WF3 priority');
 check('sic1 now sees the button DISABLED and why', (await btn(c,'Change priority').isDisabled())&&/last set by a Manager/.test(await c.innerText()), await c.locator('.actions').innerText());
 const po=await open('po1'); c=card(po,'WF3 priority');
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('High'); await c.locator('.formbox textarea').fill('Project level priority'); await c.locator('.formbox .go').click(); await T(po);
 await mgr.reload(); await T(mgr,700); await s1.reload(); await T(s1,700); const m2b=await open('manager2');
 check('after PO sets High: manager1, manager2 and sic1 are locked out (disabled)', (await btn(card(mgr,'WF3 priority'),'Change priority').isDisabled())&&(await btn(card(m2b,'WF3 priority'),'Change priority').isDisabled())&&(await btn(card(s1,'WF3 priority'),'Change priority').isDisabled()));
 const gm=await open('gm1'); c=card(gm,'WF3 priority');
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('Medium'); await c.locator('.formbox textarea').fill('General Manager decision'); await c.locator('.formbox .go').click(); await T(gm);
 await po.reload(); await T(po,700);
 check('after GM sets: PO is locked out and the note names the General Manager', (await btn(card(po,'WF3 priority'),'Change priority').isDisabled())&&/General Manager/.test(await card(po,'WF3 priority').locator('.lock-note').innerText()));
 check('GM can change again (same rank)', await (async()=>{await gm.reload();await T(gm,700);return !(await btn(card(gm,'WF3 priority'),'Change priority').isDisabled());})());
 check('DB priority audit has all 4 changes with reasons', +db(`select count(*) from exception_audit a join shift_exceptions e on e.id=a.exception_id where e.description='WF3 priority' and a.action='priority_changed' and length(a.note)>=5`)===4);
 // database is authoritative: stale page, DB refuses, exact error shown
 mk('WF4 stale lock','Coal Despatch','Weather','Siding 1','Low');
 s1=await open('sic1'); c=card(s1,'WF4 stale lock');
 check('sic1 sees the button enabled (page is not yet aware)', !(await btn(c,'Change priority').isDisabled()));
 asUser('manager1@example.com',`select change_priority((select id from shift_exceptions where description='WF4 stale lock'),'High','Manager escalation now')`);
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('Medium'); await c.locator('.formbox textarea').fill('Disagree with the escalation'); await c.locator('.formbox .go').click(); await T(s1);
 const er=await c.locator('.inline-err').innerText();
 check('database refusal shown exactly, in a friendly message', /Sorry, that did not work\. Error: This priority was set by a Manager\. Only a Manager or higher can change it\./.test(er), er);
 check('  ...and the priority did not change', row('WF4 stale lock').endsWith('High|Low'));

 console.log('=== 10. OVERDUE and analytics follow CURRENT priority');
 const oldId=db(`select id from shift_exceptions where status='Open' and current_priority='High' and created_at < now() - interval '2 hours' and description like 'Demo:%' limit 1`);
 const oldDesc=db(`select description from shift_exceptions where id='${oldId}'`);
 let g=await open('gm1'); c=card(g,oldDesc);
 check('old High record shows OVERDUE', /OVERDUE/.test(await c.innerText()));
 const before=await g.evaluate(()=>[...document.querySelectorAll('.card .n')].map(e=>+e.textContent));
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('Low'); await c.locator('.formbox textarea').fill('Downgraded after site check'); await c.locator('.formbox .go').click(); await T(g);
 c=card(g,oldDesc); const after=await g.evaluate(()=>[...document.querySelectorAll('.card .n')].map(e=>+e.textContent));
 check('after High -> Low: OVERDUE gone, badge Low', !/OVERDUE/.test(await c.innerText())&&(await c.locator('.badge.Low').count())===1);
 check('High Priority KPI dropped by 1; other KPIs unchanged', after[1]===before[1]-1&&after[0]===before[0]&&after[2]===before[2], JSON.stringify([before,after]));
 const t3sql=db(`select category||' - '||issue_type||' | '||current_priority||' priority · '||impact_minutes||' min impact' from shift_exceptions where status<>'Resolved' order by case current_priority when 'High' then 0 when 'Medium' then 1 else 2 end, impact_minutes desc, created_at asc limit 3`).split('\n');
 const t3ui=await g.evaluate(()=>[...document.querySelectorAll('#top3 .item')].map(e=>e.querySelector('.top span').textContent.replace(/^\d/,'')+' | '+e.querySelector('.reason').textContent));
 check('Top 3 still exact after the priority change (uses current priority)', JSON.stringify(t3ui)===JSON.stringify(t3sql), JSON.stringify(t3ui)+' vs '+JSON.stringify(t3sql));
 await btn(c,'Change priority').click(); await c.locator('.formbox select').selectOption('High'); await c.locator('.formbox textarea').fill('Back to High after review'); await c.locator('.formbox .go').click(); await T(g);
 c=card(g,oldDesc);
 check('Low -> High: OVERDUE returns (old record)', /OVERDUE/.test(await c.innerText()));

 console.log('=== 11. remarks');
 mk('WF5 remarks'); o1=await open('overman1'); c=card(o1,'WF5 remarks');
 check('overman: operational remark button only', (await btn(c,'Add operational remark').count())===1&&(await btn(c,'Add management remark').count())===0);
 await btn(c,'Add operational remark').click(); await c.locator('.formbox textarea').fill('Crew briefed, work under way'); await c.locator('.formbox .go').click(); await T(o1);
 check('operational remark appears on the card', /Crew briefed, work under way/.test(await card(o1,'WF5 remarks').innerText()));
 const mm=await open('manager1'); c=card(mm,'WF5 remarks');
 check('manager: sees the operational remark, has only a management remark button', /Crew briefed/.test(await c.innerText())&&(await btn(c,'Add management remark').count())===1&&(await btn(c,'Add operational remark').count())===0);
 await btn(c,'Add management remark').click(); await c.locator('.formbox textarea').fill('Escalate if not done by noon'); await c.locator('.formbox .go').click(); await T(mm);
 check('management remark appears for the manager with a Management tag', /Escalate if not done by noon/.test(await card(mm,'WF5 remarks').innerText())&&(await card(mm,'WF5 remarks').locator('.kind').count())===1);
 await o1.reload(); await T(o1,700);
 check('overman1 never sees the management remark', !(await o1.locator('body').innerText()).includes('Escalate if not done by noon'));
 s1=await open('sic1'); c=card(s1,'WF5 remarks');
 check('sic1 sees both remarks; no edit or delete controls anywhere', /Crew briefed/.test(await c.innerText())&&/Escalate if not done/.test(await c.innerText())&&(await s1.locator('button',{hasText:/^(Edit|Delete)/}).count())===0);
 check('remarks are add-only in the DB', +db(`select count(*) from exception_remarks r join shift_exceptions e on e.id=r.exception_id where e.description='WF5 remarks'`)===2);

 console.log('=== 12. exact database errors shown when the page is stale');
 mk('WF6 stale start'); o1=await open('overman1'); c=card(o1,'WF6 stale start');
 asUser('sic1@example.com',`select start_exception((select id from shift_exceptions where description='WF6 stale start'))`);
 await btn(c,'Start').click(); await T(o1);
 check('Start on a record already started: database message shown on the card and in the pop-up', /Only an Open exception can be started \(this one is In progress\)/.test(await c.locator('.inline-err').innerText())&&/Sorry, that did not work/.test(await toast(o1)));
 mk('WF8 stale closure'); asUser('sic1@example.com',`select start_exception((select id from shift_exceptions where description='WF8 stale closure'))`);
 o1=await open('overman1'); c=card(o1,'WF8 stale closure');
 asUser('sic1@example.com',`select resolve_exception((select id from shift_exceptions where description='WF8 stale closure'),'Resolved by shift crew')`);
 await btn(c,'Request closure').click(); await c.locator('.formbox textarea').fill('Verified in field'); await c.locator('.formbox .go').click(); await T(o1);
 check('Request closure on a Resolved record: DB error shown', /Closure can only be requested for an In progress exception \(this one is Resolved\)/.test(await c.locator('.inline-err').innerText()), await c.locator('.inline-err').innerText());
 const o2b=await open('overman2'); c=card(o2b,'WF6 stale start');
 psql(`update profiles set active=false where user_id=(select id from auth.users where email='overman2@example.com')`);
 await btn(c,'Request closure').click(); await c.locator('.formbox textarea').fill('Verified in field'); await c.locator('.formbox .go').click(); await T(o2b);
 check('switched-off account: database message shown', /Your account has no active role/.test(await c.locator('.inline-err').innerText()));
 psql(`update profiles set active=true where user_id=(select id from auth.users where email='overman2@example.com')`);
 check('no page errors anywhere', [o1,o2,s1,m1,m2,mgr,po,gm].every(p=>p.errs.length===0), [o1,o2,s1,m1,m2,mgr,po,gm].map(p=>p.errs.join(';')).join('|'));
 await done();
})();
