source "$(dirname "${BASH_SOURCE[0]:-$0}")/../lib/env.sh"

source $LIB/perm_test.sh
echo "=== A. before lockdown: workflow and permissions"
err "anon cannot read profiles" "permission denied" anon "select * from profiles"
err "anon cannot read audit" "permission denied" anon "select * from exception_audit"
err "anon cannot call create_exception" "permission denied" anon "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',5,'Low')"
val "overman1 database role" "overman" overman1 "select my_access()->>'role'"
val "manager2 can_operate" "true" manager2 "select my_access()->>'can_operate'"
val "anon-only unlinked user shows nothing" "" postgres "select ''"

# create exceptions
OV1=$($PSQL -c "set role authenticated; select set_config('request.jwt.claim.sub','${UID_[overman1]}',false); select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Coal shortage','Rake waiting',80,'High')" | tail -1)
echo "created (overman1): $OV1"
err "manager cannot create" "Only an Overman" manager1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',5,'Low')"
err "po cannot create" "Only an Overman" po1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',5,'Low')"
err "gm cannot create" "Only an Overman" gm1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',5,'Low')"
err "bad issue type for category" "does not belong" overman1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Potholes','x',5,'Low')"
err "bad priority" "Low, Medium or High" overman1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',5,'Urgent')"
err "bad minutes" "between 0 and 1440" overman1 "select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','x',9999,'Low')"
ok  "sic can create" sic1 "select create_exception((select shift_clock()->>'shift'),'Haul Road A','Haul Road','Potholes','Deep holes',40,'Medium')"

err "direct update blocked (signed in)" "Direct changes" overman1 "update shift_exceptions set status='Resolved' where id='$OV1'"
err "direct delete blocked (signed in)" "" overman1 "delete from shift_exceptions where id='$OV1'"
ok  "reported priority stored" overman1 "select 1"
val "reported=current=urgency at creation" "High|High|High" postgres "select reported_priority||'|'||current_priority||'|'||urgency from shift_exceptions where id='$OV1'"

echo "--- start / closure / resolve"
err "sic cannot resolve an Open one" "In progress exception" sic1 "select resolve_exception('$OV1','done well')"
ok  "overman2 can Start" overman2 "select start_exception('$OV1')"
err "cannot start twice" "Only an Open" sic1 "select start_exception('$OV1')"
err "manager1 (no operate) cannot start" "cannot Start" manager1 "select start_exception('$OV1')"
err "closure request needs note" "at least 5" overman1 "select request_closure('$OV1','ok')"
err "manager cannot request closure" "cannot request closure" manager1 "select request_closure('$OV1','verified in field')"
ok  "overman1 requests closure" overman1 "select request_closure('$OV1','Verified rake loaded in field')"
err "second closure request blocked" "already waiting" overman2 "select request_closure('$OV1','another note here')"
err "overman cannot Resolve" "cannot Resolve" overman1 "select resolve_exception('$OV1','done well')"
err "overman cannot Decline" "cannot decline" overman1 "select decline_closure('$OV1','not finished yet')"
err "overman cannot Reopen" "cannot reopen" overman1 "select reopen_exception('$OV1','because reasons')"
err "overman cannot change priority" "cannot change priority" overman1 "select change_priority('$OV1','Low','downgrade please')"
err "decline needs reason" "at least 5" sic1 "select decline_closure('$OV1','no')"
ok  "sic declines closure" sic1 "select decline_closure('$OV1','Rake not fully loaded yet')"
val "closure fields cleared after decline" "|" postgres "select coalesce(closure_requested_by::text,'')||'|'||coalesce(closure_requested_at::text,'') from shift_exceptions where id='$OV1'"
ok  "overman1 requests closure again" overman1 "select request_closure('$OV1','Rake fully loaded now')"
val "closure fields set" "t" postgres "select (closure_requested_by is not null and closure_requested_at is not null) from shift_exceptions where id='$OV1'"
err "manager1 cannot resolve" "cannot Resolve" manager1 "select resolve_exception('$OV1')"
ok  "sic resolves with existing request, no note" sic1 "select resolve_exception('$OV1')"
val "resolved fields set" "Resolved|t|t" postgres "select status||'|'||(resolved_at is not null)||'|'||(resolved_by is not null) from shift_exceptions where id='$OV1'"
err "cannot Resolve twice" "In progress exception" sic1 "select resolve_exception('$OV1')"

echo "--- resolve WITHOUT a closure request needs a note"
OV3=$($PSQL -c "set role authenticated; select set_config('request.jwt.claim.sub','${UID_[overman1]}',false); select create_exception((select shift_clock()->>'shift'),'MDP Junction','Dust Suppression','Heavy dust','Dusty',30,'Low')" | tail -1)
ok  "sic starts" sic1 "select start_exception('$OV3')"
err "resolve without request and without note" "resolution note" sic1 "select resolve_exception('$OV3')"
err "resolve with short note" "at least 5" sic1 "select resolve_exception('$OV3','ok')"
ok  "resolve with note" sic1 "select resolve_exception('$OV3','Sprinkling done, dust cleared')"

echo "--- reopen"
err "overman cannot reopen (again)" "cannot reopen" overman1 "select reopen_exception('$OV1','because reasons')"
err "reopen needs reason" "at least 5" sic1 "select reopen_exception('$OV1','no')"
err "manager1 (no operate) cannot reopen" "cannot reopen" manager1 "select reopen_exception('$OV1','needs a recheck')"
ok  "sic reopens" sic1 "select reopen_exception('$OV1','Rake loading was incomplete')"
val "reopen cleared the four fields, status Open" "Open|||" postgres "select status||'|'||coalesce(resolved_at::text,'')||'|'||coalesce(closure_requested_at::text,'')||'|'||coalesce(resolved_by::text,'') from shift_exceptions where id='$OV1'"
err "reopen a non-resolved one" "Only a Resolved" sic1 "select reopen_exception('$OV1','again for no reason')"
ok  "manager2 (can_operate) starts" manager2 "select start_exception('$OV1')"
ok  "overman1 requests closure (3rd)" overman1 "select request_closure('$OV1','Loaded and verified again')"
ok  "manager2 (can_operate) declines" manager2 "select decline_closure('$OV1','Weighment missing')"
ok  "overman1 requests closure (4th)" overman1 "select request_closure('$OV1','Weighment now done')"
ok  "manager2 (can_operate) resolves" manager2 "select resolve_exception('$OV1')"
ok  "manager2 (can_operate) reopens" manager2 "select reopen_exception('$OV1','Second recheck needed')"

echo "--- priority lock (GM > PO > Manager > SIC)"
ok  "sic sets Medium" sic1 "select change_priority('$OV1','Medium','Field check shows less severe')"
err "reason too short" "at least 5" sic1 "select change_priority('$OV1','Low','no')"
err "same value" "already" sic1 "select change_priority('$OV1','Medium','same again please')"
ok  "manager1 may override SIC (sets Low)" manager1 "select change_priority('$OV1','Low','Manager review, minor')"
err "SIC cannot override Manager" "set by a Manager" sic1 "select change_priority('$OV1','High','I disagree with manager')"
ok  "po sets High" po1 "select change_priority('$OV1','High','Project level priority')"
err "Manager cannot override PO" "set by a Project Officer" manager1 "select change_priority('$OV1','Medium','I disagree with PO')"
err "manager2 cannot override PO" "set by a Project Officer" manager2 "select change_priority('$OV1','Medium','I disagree with PO')"
err "SIC cannot override PO" "set by a Project Officer" sic1 "select change_priority('$OV1','Low','I disagree with PO')"
ok  "gm sets Medium" gm1 "select change_priority('$OV1','Medium','General Manager decision')"
err "PO cannot override GM" "set by a General Manager" po1 "select change_priority('$OV1','High','I disagree with GM')"
err "Manager cannot override GM" "set by a General Manager" manager1 "select change_priority('$OV1','High','I disagree with GM')"
ok  "GM may change again (same rank)" gm1 "select change_priority('$OV1','High','Escalated after review')"
val "reported priority never overwritten" "High" postgres "select reported_priority from shift_exceptions where id='$OV1'"
val "urgency mirrors current priority" "High|High" postgres "select current_priority||'|'||urgency from shift_exceptions where id='$OV1'"
val "priority_changed_by_role recorded" "general_manager" postgres "select priority_changed_by_role from shift_exceptions where id='$OV1'"
val "priority audit lines" "7" postgres "select count(*) from exception_audit where exception_id='$OV1' and action='priority_changed'"

echo "--- remarks"
ok  "overman operational remark" overman1 "select add_remark('$OV1','operational','Crew informed at site')"
err "overman cannot add management remark" "cannot add management" overman1 "select add_remark('$OV1','management','Nice work')"
ok  "manager management remark" manager1 "select add_remark('$OV1','management','Watch this closely')"
err "manager cannot add operational remark" "cannot add operational" manager1 "select add_remark('$OV1','operational','Crew informed')"
err "sic cannot add management remark" "cannot add management" sic1 "select add_remark('$OV1','management','My view')"
ok  "sic operational remark" sic1 "select add_remark('$OV1','operational','Shift plan changed')"
ok  "po management remark" po1 "select add_remark('$OV1','management','Review tomorrow')"
ok  "gm management remark" gm1 "select add_remark('$OV1','management','Approved to continue')"
err "remark too short" "at least 3" sic1 "select add_remark('$OV1','operational','a')"
err "overman remark on Resolved" "not Resolved" overman1 "select add_remark('$OV3','operational','late remark here')"
ok  "sic remark on Resolved" sic1 "select add_remark('$OV3','operational','Follow-up noted')"

echo "--- history is append-only"
err "remark cannot be updated (signed in)" "" overman1 "update exception_remarks set body='changed' where exception_id='$OV1'"
err "remark cannot be deleted (owner too)" "append-only" postgres "delete from exception_remarks"
err "audit cannot be updated (owner too)" "append-only" postgres "update exception_audit set note='x'"
err "audit cannot be deleted (owner too)" "append-only" postgres "delete from exception_audit"
err "audit cannot be truncated" "append-only" postgres "truncate exception_audit"
err "authenticated cannot write audit" "permission denied" overman1 "insert into exception_audit(exception_id,action) values ('$OV1','x')"
err "authenticated cannot write remarks" "permission denied" overman1 "insert into exception_remarks(exception_id,kind,body,author_name,author_role) values ('$OV1','operational','forged','x','y')"
err "authenticated cannot write profiles" "permission denied" overman1 "update profiles set role='general_manager'"

echo "--- signed-out (anon) rules that already hold before 05"
err "anon: cannot change description" "cannot be edited" anon "update shift_exceptions set description='hacked' where id='$OV1'"
err "anon: cannot change reported priority" "cannot be edited" anon "update shift_exceptions set reported_priority='Low' where id='$OV1'"
err "anon: cannot change urgency" "cannot be edited" anon "update shift_exceptions set urgency='Low' where id='$OV1'"
err "anon: cannot delete" "" anon "delete from shift_exceptions where id='$OV1'"
echo "PASS=$PASS FAIL=$FAIL"
