source "$(dirname "${BASH_SOURCE[0]:-$0}")/../lib/env.sh"

source $LIB/perm_test.sh
MSG="cannot confirm or decline your own closure request"
mkx(){ $PSQL -c "set role authenticated; select set_config('request.jwt.claim.sub','${UID_[overman1]}',false); select create_exception((select shift_clock()->>'shift'),'Siding 1','Coal Despatch','Weather','$1',20,'Medium')" | tail -1; }
st(){ $PSQL -c "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$1'"; }
echo "=== E. maker-checker: the requester cannot decline or confirm their own closure request"
A=$(mkx 'MC one'); 
ok  "overman2 starts" overman2 "select start_exception('$A')"
ok  "sic1 requests closure" sic1 "select request_closure('$A','Verified on site by shift in-charge one')"
AUD=$($PSQL -c "select count(*) from exception_audit where exception_id='$A'")
err "sic1 (requester) cannot DECLINE own request" "$MSG" sic1 "select decline_closure('$A','I want to decline my own request')"
err "sic1 (requester) cannot CONFIRM (Resolve, no note) own request" "$MSG" sic1 "select resolve_exception('$A')"
err "sic1 (requester) cannot CONFIRM (Resolve, with note) own request" "$MSG" sic1 "select resolve_exception('$A','I resolve my own request')"
val "refused attempts changed nothing (state + audit count)" "In progress|Test Shift In-Charge One||$AUD" postgres "select status||'|'||closure_requested_by_name||'|'||coalesce(resolved_by_name,'')||'|'||(select count(*) from exception_audit where exception_id='$A') from shift_exceptions where id='$A'"
err "exact message text" "You cannot confirm or decline your own closure request. Another Shift In-Charge or authorised Manager must review it." sic1 "select resolve_exception('$A')"
err "overman cannot decline (role rule intact)" "cannot decline" overman1 "select decline_closure('$A','not allowed for overman')"
err "overman cannot resolve (role rule intact)" "cannot Resolve" overman1 "select resolve_exception('$A')"
err "manager1 (no can_operate) still cannot review" "cannot decline" manager1 "select decline_closure('$A','manager without operate')"
err "manager1 (no can_operate) still cannot resolve" "cannot Resolve" manager1 "select resolve_exception('$A')"
err "non-requester still needs a 5+ character reason" "at least 5" sic2 "select decline_closure('$A','no')"
ok  "sic2 DECLINES sic1's request" sic2 "select decline_closure('$A','Site check shows more work is needed')"
val "declined: request cleared" "In progress||" postgres "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$A'"
ok  "sic1 requests again" sic1 "select request_closure('$A','Work completed and re-checked by sic1')"
ok  "sic2 CONFIRMS (Resolve, no second reason) sic1's request" sic2 "select resolve_exception('$A')"
val "resolved by sic2, closure fields cleared" "Resolved||Test Shift In-Charge Two" postgres "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$A'"
val "history keeps the closure request and the decline" "t" postgres "select count(*) filter (where action='closure_requested')=2 and count(*) filter (where action='closure_declined')=1 and count(*) filter (where action='resolved')=1 from exception_audit where exception_id='$A'"

echo "--- the other way round: sic2 requests, sic1 reviews"
B=$(mkx 'MC two'); ok "sic1 starts" sic1 "select start_exception('$B')"
ok  "sic2 requests closure" sic2 "select request_closure('$B','Verified on site by shift in-charge two')"
err "sic2 (requester) cannot DECLINE own request" "$MSG" sic2 "select decline_closure('$B','declining my own request')"
err "sic2 (requester) cannot CONFIRM own request" "$MSG" sic2 "select resolve_exception('$B')"
ok  "sic1 DECLINES sic2's request" sic1 "select decline_closure('$B','Please add the weighbridge slip')"
ok  "sic2 requests again" sic2 "select request_closure('$B','Weighbridge slip attached and verified')"
ok  "sic1 CONFIRMS sic2's request" sic1 "select resolve_exception('$B')"
val "resolved by sic1" "Resolved||Test Shift In-Charge One" postgres "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$B'"

echo "--- Manager with can_operate may review; Overman requests are reviewed by others"
C=$(mkx 'MC three'); ok "manager2 starts" manager2 "select start_exception('$C')"
ok  "sic1 requests closure" sic1 "select request_closure('$C','Checked and complete per sic1')"
ok  "manager2 (can_operate) DECLINES a Shift In-Charge request" manager2 "select decline_closure('$C','Manager wants a photo first')"
ok  "sic1 requests again" sic1 "select request_closure('$C','Photo added and verified again')"
ok  "manager2 (can_operate) CONFIRMS a Shift In-Charge request" manager2 "select resolve_exception('$C')"
val "resolved by manager2" "Resolved||Test Manager Two (operate)" postgres "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$C'"
D2=$(mkx 'MC four'); ok "overman1 starts" overman1 "select start_exception('$D2')"
ok  "overman1 requests closure" overman1 "select request_closure('$D2','Overman verified in the field')"
err "overman1 (requester, overman) still cannot confirm" "cannot Resolve" overman1 "select resolve_exception('$D2')"
ok  "manager2 (can_operate) confirms an Overman request" manager2 "select resolve_exception('$D2')"
E2=$(mkx 'MC five'); ok "sic1 starts" sic1 "select start_exception('$E2')"
ok  "overman2 requests closure" overman2 "select request_closure('$E2','Overman two verified it')"
ok  "sic1 (not the requester) confirms an Overman request" sic1 "select resolve_exception('$E2')"

echo "--- no closure request: a Shift In-Charge may still resolve directly with a note"
F=$(mkx 'MC six'); ok "sic1 starts" sic1 "select start_exception('$F')"
err "direct resolve without note refused" "resolution note" sic1 "select resolve_exception('$F')"
ok  "sic1 resolves directly with a note" sic1 "select resolve_exception('$F','Cleared by the crew, nothing pending')"
val "direct resolve worked" "Resolved||Test Shift In-Charge One" postgres "select status||'|'||coalesce(closure_requested_by_name,'')||'|'||coalesce(resolved_by_name,'') from shift_exceptions where id='$F'"
echo "PASS=$PASS FAIL=$FAIL"
